openapi: 3.0.0
info:
  title: 06-JOBS-API
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
        - role
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
      example:
        name: admin
        email: admin@gmail.com
        password: admin
        role: admin
    LoginRequest:
      title: LoginRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: ismaeel@gmail.com
        password: ismaeel
    CreateJobRequest:
      title: CreateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Random
        position: FullStack
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Random
        position: FullStack

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      security:
        - bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      responses:
        '200':
          description: User registered successfully

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Login successful
      security: []

  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      operationId: CreateJob
      security:
        - bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRequest'
        required: true
      responses:
        '200':
          description: Job created successfully

    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      security:
        - bearer: []
      responses:
        '200':
          description: Retrieved all jobs

  /jobs/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      security:
        - bearer: []
      responses:
        '200':
          description: Retrieved single job

    patch:
      tags:
        - Jobs
      summary: Update a Job
      operationId: UpdateJob
      security:
        - bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
        required: true
      responses:
        '200':
          description: Job updated successfully

    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      security:
        - bearer: []
      responses:
        '200':
          description: Job deleted successfully

security: []
tags:
  - name: Auth
    description: ''
  - name: Jobs
    description: ''
